// <auto-generated />
using System;
using JwtPrpject.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtPrpject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023105047_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JwtPrpject.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b016ce4d-88a5-4537-85bf-df8768d7d65c"),
                            Name = "98YM"
                        },
                        new
                        {
                            Id = new Guid("35556ee0-6031-4db2-841b-834275b6876c"),
                            Name = "BEAK"
                        },
                        new
                        {
                            Id = new Guid("1707b145-2654-46dd-866d-8bef534be08b"),
                            Name = "AREH"
                        },
                        new
                        {
                            Id = new Guid("c0a16c13-acf5-4720-9ea0-bede63446981"),
                            Name = "8ELM"
                        });
                });

            modelBuilder.Entity("JwtPrpject.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b974dce7-9d01-4c9e-bb00-5834085eda7a"),
                            Email = "N3PSOMW9@gmail.com",
                            Name = "4UNX",
                            Password = "W3WZN04XPK"
                        },
                        new
                        {
                            Id = new Guid("dd217136-ad6f-4dad-aa63-37f87967fdaa"),
                            Email = "9BQHI40V@gmail.com",
                            Name = "6YGM",
                            Password = "60HDG01K5Z"
                        },
                        new
                        {
                            Id = new Guid("ffd61845-3503-4ffd-a5bd-2ecd1e7f84a1"),
                            Email = "ZHDYX84A@gmail.com",
                            Name = "XR0T",
                            Password = "QV7R1IDFR0"
                        },
                        new
                        {
                            Id = new Guid("0df91b27-c883-4512-81ca-ad3fcb9ad299"),
                            Email = "YUODQM5E@gmail.com",
                            Name = "12Q6",
                            Password = "D7SOON09HF"
                        },
                        new
                        {
                            Id = new Guid("2cc87196-216c-48c1-a2b4-6b4479f56fba"),
                            Email = "4LO12NPO@gmail.com",
                            Name = "YUHL",
                            Password = "F18163AAG7"
                        },
                        new
                        {
                            Id = new Guid("b12957a0-d6ae-4ef6-8f28-51136664b2d7"),
                            Email = "D1O2A4J9@gmail.com",
                            Name = "I9QM",
                            Password = "YBMNY6N27G"
                        },
                        new
                        {
                            Id = new Guid("04f330b6-9bb5-48bd-9236-2a80a490091d"),
                            Email = "SAAHZ7VG@gmail.com",
                            Name = "6JRE",
                            Password = "ULAFX6PLLN"
                        },
                        new
                        {
                            Id = new Guid("d6bfaeff-5ba9-463e-a11a-2240ccc7d866"),
                            Email = "731E483Z@gmail.com",
                            Name = "RNGH",
                            Password = "QB1SDV27VO"
                        },
                        new
                        {
                            Id = new Guid("b3c66201-3845-4696-b62b-2ae8bad5c43d"),
                            Email = "C2KKYHCD@gmail.com",
                            Name = "EVY2",
                            Password = "LYIY79SH2R"
                        },
                        new
                        {
                            Id = new Guid("e1bdda8b-12b2-4580-a2e1-64c5aa63b5b2"),
                            Email = "90VGKQ0Q@gmail.com",
                            Name = "UO9E",
                            Password = "ZXH9VJECX0"
                        },
                        new
                        {
                            Id = new Guid("4d33a550-e32a-4429-8e2a-e295bb130a9c"),
                            Email = "REXFQLLX@gmail.com",
                            Name = "D1RS",
                            Password = "0ETVUBYKX8"
                        },
                        new
                        {
                            Id = new Guid("674f7b19-caab-41ed-bca7-b0761c53e129"),
                            Email = "QT5AA4EN@gmail.com",
                            Name = "0RQF",
                            Password = "YDZ6RJSTJU"
                        },
                        new
                        {
                            Id = new Guid("c7400323-7b9e-4919-9147-d024f550ba12"),
                            Email = "X247JUNP@gmail.com",
                            Name = "PNI2",
                            Password = "0EGBYM7EQ9"
                        },
                        new
                        {
                            Id = new Guid("0194d703-52e1-4ff4-9fce-07001b4139df"),
                            Email = "4L288LST@gmail.com",
                            Name = "DTTZ",
                            Password = "FEQVQX6EQN"
                        },
                        new
                        {
                            Id = new Guid("aff57280-094e-4d72-a406-16b061873447"),
                            Email = "NULGVNBY@gmail.com",
                            Name = "EY41",
                            Password = "69DEM3Z2HP"
                        },
                        new
                        {
                            Id = new Guid("c7951a10-73fc-41b9-abd0-7da82e905631"),
                            Email = "H0Z7YRUT@gmail.com",
                            Name = "MGBJ",
                            Password = "KOX9TH6PGT"
                        },
                        new
                        {
                            Id = new Guid("c7880f16-031d-438b-a483-7d3ab2796c86"),
                            Email = "9OL0F9IV@gmail.com",
                            Name = "3NBM",
                            Password = "MYIQMVL5JY"
                        },
                        new
                        {
                            Id = new Guid("906e9253-974e-434d-9583-9a24f1054862"),
                            Email = "HYYIN6A7@gmail.com",
                            Name = "D796",
                            Password = "6R6EHPYP4V"
                        },
                        new
                        {
                            Id = new Guid("c6e31221-f75b-4904-bed1-0b8e01170e8e"),
                            Email = "VZ200UJW@gmail.com",
                            Name = "0SE8",
                            Password = "T3UYH556TX"
                        },
                        new
                        {
                            Id = new Guid("2f3d9ca0-64b9-4b76-b6b5-b103f30502a6"),
                            Email = "21YNGF2Z@gmail.com",
                            Name = "BOXK",
                            Password = "R2O9TZNZUG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
